apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: apptest
  labels:
    monitoring: enabled
    app: app-test
spec:
  selector:
    app: app-test
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 8089
  type: ClusterIP