name: Build and Deploy apptest
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: wellingtonns/pipeline-template/.github/workflows/build-push.yml@main
    with:
      IMAGE_NAME: welignton/site-test
      APP_NAME: site-test
    secrets: inherit

  sync-argocd:
    needs: build
    uses: wellingtonns/pipeline-template/.github/workflows/argocd-sync.yml@main
    with:
      APP_NAME: site-test
    secrets: inherit
